name: FlightExamples INTs

on:
  push:
    branches: [ devel, release/**, pattern/** ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'


jobs:
  build:
    name: ""
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/fprime-community/fprime-examples-builder:latest

    steps:
      - name: "Checkout Examples repo"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Install ZLIB development libraries"
        run: |
          sed -i 's|http://archive.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list.d/ubuntu.sources || sed -i 's|http://archive.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list
          sed -i 's|http://security.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list.d/ubuntu.sources || sed -i 's|http://security.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list
          apt-get update && apt-get install -y zlib1g-dev zlib1g-dev:arm64

      - name: "Set up F Prime environment"
        run: |
          curl -sSL https://raw.githubusercontent.com/nasa/fprime/devel/requirements.txt -o /tmp/requirements.txt
          sed -i 's/crcmod/crcmod-plus/g' /tmp/requirements.txt
          pip3 install --break-system-packages -U -r /tmp/requirements.txt

      - name: "Build & Tests"
        uses: fprime-community/project-builder@main
        with:
          run_integration_tests: true
          build_location: ./FlightExamples
          fprime_location: ./FlightExamples/lib/fprime
          fprime_version: devel
          skip_requirements_install: true
          extra_generate_args: "-DFPRIME_EXAMPLES_USE_OPENCV=ON"
          extra_test_args: "-s -v"